package exbana

// Writer is an interface for writing objects generated by a pattern.
// T is the type of the objects being written.
type Writer[T any] interface {
	// Write writes the specified objects to the output.
	Write(...T) error

	// Finish signals that the generation is complete.
	Finish() error
}
